services:
  redis:
    image: redis:8.4-alpine
    container_name: redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgresql:
    image: postgres:18-alpine
    container_name: postgresql
    restart: always
    ports:
      - "${SQL_PORT}:5432"
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DATABASE}

      EXPORTER_USER: ${SQL_EXPORTER_USER}
      EXPORTER_PASSWORD: ${SQL_EXPORTER_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_USER} -d ${SQL_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./deployment/postgres-init/init-exporter.sh:/docker-entrypoint-initdb.d/init-exporter.sh

  app:
    build: .
    container_name: gomonitor-app
    restart: always
    ports:
      - "${APP_PORT:-8080}:8080"
    labels:
      logging: "enabled"
    env_file:
      - .env
    environment:
      - ENVIRONMENT=production
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./deployment/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  
  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./deployment/observability/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/var/tempo
    ports:
      - "3200:3200" # Tempo
      - "9095:9095" # Tempo gRPC
      - "4317:4317" # otlp gRPC 
      - "4318:4318" # otlp http
      
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: ["-config.file=/etc/loki/local-config.yaml"]
    volumes:
      - ./deployment/observability/loki/loki.yaml:/etc/loki/local-config.yaml
      - loki_data:/loki
      
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"   
      - "3500:3500"
    command:
      - "run"
      - "--server.http.listen-addr=0.0.0.0:12345"
      - "--storage.path=/var/lib/alloy/data"
      - "/etc/config.alloy"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./deployment/observability/alloy/config.alloy:/etc/config.alloy
    depends_on:
      - loki
  
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: postgresql://${SQL_EXPORTER_USER}:${SQL_EXPORTER_PASSWORD}@postgresql:5432/${SQL_DATABASE}?sslmode=disable
    ports:
      - "9187:9187"
    depends_on:
      - postgresql

  redis-exporter:
    image: oliver006/redis_exporter
    environment:
      REDIS_ADDR: "redis:6379"
    ports:
      - "9121:9121"
    depends_on:
      - redis

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./deployment/observability/grafana/provisioning:/etc/grafana/provisioning
      - ./deployment/observability/grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  loki_data:
  postgres_data:
  tempo_data: