global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gomonitor-app"
    static_configs:
      - targets: ["gomonitor-app:8080"]

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]
